server:
  port: 2333

lavalink:
  server:
    password: "1234"
    sources:
      youtube: false   # ‚Üê Desactivamos el extractor viejo
      soundcloud: true
      http: true
      twitch: true
      bandcamp: true
    bufferDurationMs: 400
    youtubeSearchEnabled: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    resuming:
      enabled: false
    gc-warnings: true

  plugins:
    - name: youtube
      path: plugins/youtube-plugin-1.13.3.jar
